function [cvs,cnames,fitresult, gof] = createPVFit(a, b, probLevel)
%CREATEFIT(A,B)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: a
%      Y Output: b
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Dec-2025 17:29:29



    %% Fit: 'untitled fit 1'.
    [xData, yData, scalex, scaley] = prepareCurveData( a, b );
    
    % Set up fittype and options.
    ft = fittype( 'A*(m*(1./(1+4*((x-xc)/w).^2))+(1-m)*exp(-4*log(2)*((x-xc)/w).^2))', 'independent', 'x', 'dependent', 'y' );
    opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
    % parameters Amplitude, Mixture, spread, center
    opts.Display = 'Off';
    opts.Lower = [0.5*max(yData) 0 0 min(xData)];
    opts.StartPoint = [max(yData) 0.5 max(xData)/2 0];
    opts.Upper = [1.5*max(yData) 1 max(xData) max(xData)];
    
    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );
    cvs=[coeffvalues(fitresult)',confint(fitresult, probLevel)'];
    cvs(1,:)=cvs(1,:).*scaley;
    cvs(3:4,:)=cvs(3:4,:).*scalex;
    cnames=coeffnames(fitresult);
end

function [xData,yData,scalex,scaley] = prepareCurveData( a, b )
    scalex=sqrt(mean(a.^2));
    xData=a/scalex;
    scaley=sum(b);
    yData=b/scaley;
end